#!/bin/bash
# Installs and uninstalls discorddownloader to /usr/bin/discorddownloader using wget

main () {
    case $1 in
        install)
            read -p "Install discorddownloader to /usr/bin/discorddownloader? Y/N " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Nn]$ ]]; then
                echo "discorddownloader was not installed."
                exit 0
            fi
            wget -O /tmp/discorddownloader https://raw.githubusercontent.com/simoniz0r/discorddownloader/master/discorddownloader.sh
            if [ -f "/tmp/discorddownloader" ]; then
                wget -O /tmp/discorddownloader.png https://raw.githubusercontent.com/simoniz0r/discorddownloader/master/discorddownloader.png
                if [ -f "/tmp/discorddownloader.png" ]; then
                    wget -O /tmp/discorddownloader.desktop https://raw.githubusercontent.com/simoniz0r/discorddownloader/master/discorddownloader.desktop
                        if [ -f "/tmp/discorddownloader.desktop" ]; then
                            echo "Moving discorddownloader to /usr/bin/discorddownloader"
                            mv /tmp/discorddownloader /usr/bin/discorddownloader
                            echo "Making discorddownloader executable"
                            chmod +x /usr/bin/discorddownloader
                            echo "Moving discorddownloader icon to /usr/share/icons/discorddownloader.png"
                            mv /tmp/discorddownloader.png /usr/share/icons/discorddownloader.png
                            echo "Moving .desktop file to /usr/share/applications/discorddownloader.desktop"
                            mv /tmp/discorddownloader.desktop /usr/share/applications/discorddownloader.desktop
                        else
                            echo ".desktop file download failed; try installing again."
                            rm -f /tmp/discorddownloader.sh
                            rm -f /tmp/discorddownloader.png
                            exit 0
                        fi
                else
                    echo "Icon download failed; try installing again."
                    rm -f /tmp/discorddownloader.sh
                    exit 0
                fi
            else
                echo "discorddownloader download failed; try installing again."
                exit 0
            fi
            ;;
        uninstall)
            read -p "Uninstall discorddownloader from /usr/bin/discorddownloader? Y/N " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Nn]$ ]]; then
                echo "discorddownloader was not uninstalled."
                exit 0
            fi
            if [ -f "/usr/bin/discorddownloader" ]; then
                rm -f /usr/bin/discorddownloader
                echo "discorddownloader has been removed!"
            else
                echo "/usr/bin/discorddownloader does not exist!"
            fi
            if [ -f "/usr/share/icons/discorddownloader.png" ]; then
                rm -f /usr/share/icons/discorddownloader.png
                echo "discorddownloader.png has been removed!"
            else
                echo "discorddownloader.png does not exist!"
            fi
            if [ -f "/usr/share/applications/discorddownloader.desktop" ]; then
                rm -f /usr/share/applications/discorddownloader.desktop
                echo "discorddownloader.desktop has been removed!"
            else
                echo "discorddownloader.desktop does not exist!"
            fi
            exit 0
            ;;
        *)
            echo "Usage:"
            echo "'sudo ./disorddlinst install' for installation process"
            echo "'sudo ./disorddlinst uninstall' for uninstallation process"
            exit 0
    esac
        
}

programisinstalled () {
  # set to 1 initially
  return=1
  # set to 0 if not found
  type "$1" >/dev/null 2>&1 || { return=0; }
  # return value
}

if [ "$EUID" -ne 0 ]; then
    echo "disorddlinst install and uninstall must be ran as root!"
    main "help"
    exit 0
fi
programisinstalled "wget"
if [ "$return" = "1" ]; then
    main "$1"
else
    echo "wget is not installed; cannot download discorddownloader."
fi